### ISSUE TITLE
Support Jakarta EE

### ISSUE THREAD

**Issue by spinachomes** [ebean-orm/ebean-spring-txn#35]

**Comment by spinachomes** [comment]
java.lang.ClassNotFoundException: javax.persistence.PersistenceException

**Comment by rbygrave** [comment]
Can you provide a stack trace and confirm the version of ebean being used?  (there are several versions of ebean jakarta)

**Comment by rbygrave** [comment]
I have released version `13.14.0-jakarta` of ebean-spring-txn and converted the `javax.persistence` references to `jakarta.persistence`.  Can you try that version? (In theory it should be there in about 15 minutes).

Note that we need to move this to instead be a module in https://github.com/ebean-orm/ebean so that we always release the 2 versions (javax and jakarta) going forward. I'll look to make that change and move ebean-spring-txn there.

**Comment by spinachomes** [comment]
ok, it run well with 13.14.0-jakarta ,I suggest that add this module into ebean-bom in the next version

**Comment by rbygrave** [comment]
I'll close this.
